type Referee {
  id: ID!
  userId: ID!
  fullName: String!
  email: String!
  phone: String!
  createdAt: Time
  updatedAt: Time
  deletedAt: Time
}

input NewReferee {
  userId: ID!
  fullName: String!
  email: String!
  phone: String!
}

extend type Mutation {
  createReferee(input: NewReferee!): Referee!
  updateReferee(input: Any): Referee!
}

extend type Query {
  referee(id: ID!): Referee!
  referees(userId: ID): [Referee!]!
}
