// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Activity struct {
	ID       string `json:"id" bson:"_id"`
	CourseID string `json:"courseId" bson:"courseId,omitempty"`
}

type AnswerOption struct {
	ID         string    `json:"id" bson:"_id"`
	QuestionID *string   `json:"questionId" bson:"questionId,omitempty"`
	Value      *string   `json:"value" bson:"value,omitempty"`
	Hint       *string   `json:"hint" bson:"hint,omitempty"`
	Question   *Question `json:"question" bson:"question,omitempty"`
}

type Auth struct {
	ID          string    `json:"id" bson:"_id"`
	Role        string    `json:"role" bson:"role,omitempty"`
	Email       *string   `json:"email" bson:"email,omitempty"`
	Token       string    `json:"token" bson:"token,omitempty"`
	ExpiredAt   string    `json:"expiredAt" bson:"expiredAt,omitempty"`
	Permissions []*string `json:"permissions" bson:"permissions,omitempty"`
	Username    *string   `json:"username" bson:"username,omitempty"`
	Progress    int       `json:"progress" bson:"progress,omitempty"`
}

type Course struct {
	ID          string     `json:"id" bson:"_id"`
	UserID      string     `json:"userId" bson:"userId,omitempty"`
	Author      string     `json:"author" bson:"author,omitempty"`
	Title       string     `json:"title" bson:"title,omitempty"`
	Code        string     `json:"code" bson:"code,omitempty"`
	CourseType  string     `json:"courseType" bson:"courseType,omitempty"`
	Description *string    `json:"description" bson:"description,omitempty"`
	Program     string     `json:"program" bson:"program,omitempty"`
	Semester    string     `json:"semester" bson:"semester,omitempty"`
	Year        string     `json:"year" bson:"year,omitempty"`
	Lecturer    string     `json:"lecturer" bson:"lecturer,omitempty"`
	Users       []string   `json:"users" bson:"users,omitempty"`
	Activities  []string   `json:"activities" bson:"activities,omitempty"`
	Timeline    string     `json:"timeline" bson:"timeline,omitempty"`
	Grades      string     `json:"grades" bson:"grades,omitempty"`
	Assignments []string   `json:"assignments" bson:"assignments,omitempty"`
	Videos      []string   `json:"videos" bson:"videos,omitempty"`
	Notes       []string   `json:"notes" bson:"notes,omitempty"`
	Document    []string   `json:"document" bson:"document,omitempty"`
	Status      *string    `json:"status" bson:"status,omitempty"`
	Progress    int        `json:"progress" bson:"progress,omitempty"`
	CreatedAt   *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
	DueDate     *time.Time `json:"dueDate" bson:"dueDate,omitempty"`
}

type Education struct {
	ID             string     `json:"id" bson:"_id"`
	UserID         string     `json:"userId" bson:"userId,omitempty"`
	Degree         string     `json:"degree" bson:"degree,omitempty"`
	Institution    string     `json:"institution" bson:"institution,omitempty"`
	GraduationYear string     `json:"graduationYear" bson:"graduationYear,omitempty"`
	CreatedAt      *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt      *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt      *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
}

type EvaluationCriteria struct {
	ID          string    `json:"id" bson:"_id"`
	Name        *string   `json:"name" bson:"name,omitempty"`
	CourseID    *string   `json:"courseID" bson:"courseID,omitempty"`
	MaxGrade    *int      `json:"maxGrade" bson:"maxGrade,omitempty"`
	PassGrade   *int      `json:"passGrade" bson:"passGrade,omitempty"`
	GradeLabels []*string `json:"gradeLabels" bson:"gradeLabels,omitempty"`
	Course      *Course   `json:"course" bson:"course,omitempty"`
}

type File struct {
	ID          string     `json:"id" bson:"_id"`
	UserID      string     `json:"userId" bson:"userId,omitempty"`
	Filename    string     `json:"filename" bson:"filename,omitempty"`
	Title       string     `json:"title" bson:"title,omitempty"`
	URL         string     `json:"url" bson:"url,omitempty"`
	Path        string     `json:"path" bson:"path,omitempty"`
	Size        int64      `json:"size" bson:"size,omitempty"`
	ContentType string     `json:"contentType" bson:"contentType,omitempty"`
	Category    string     `json:"category" bson:"category,omitempty"`
	CourseID    string     `json:"courseId" bson:"courseId,omitempty"`
	CreatedAt   *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
}

type Grade struct {
	ID       string `json:"id" bson:"_id"`
	CourseID string `json:"courseId" bson:"courseId,omitempty"`
}

type Mail struct {
	FromAddr string   `json:"fromAddr" bson:"fromAddr,omitempty"`
	ToAddrs  []string `json:"toAddrs" bson:"toAddrs,omitempty"`
	Subject  string   `json:"subject" bson:"subject,omitempty"`
	Body     string   `json:"body" bson:"body,omitempty"`
}

type NewAccount struct {
	FirstName string `json:"firstName" bson:"firstName,omitempty"`
	LastName  string `json:"lastName" bson:"lastName,omitempty"`
	FullName  string `json:"fullName" bson:"fullName,omitempty"`
	Email     string `json:"email" bson:"email,omitempty"`
	Password  string `json:"password" bson:"password,omitempty"`
	Role      string `json:"role" bson:"role,omitempty"`
}

type NewCourse struct {
	ID       string `json:"id" bson:"_id"`
	Title    string `json:"title" bson:"title,omitempty"`
	Code     string `json:"code" bson:"code,omitempty"`
	Type     string `json:"type" bson:"type,omitempty"`
	Program  string `json:"program" bson:"program,omitempty"`
	Semester string `json:"semester" bson:"semester,omitempty"`
	Year     string `json:"year" bson:"year,omitempty"`
}

type NewEducation struct {
	UserID         string `json:"userId" bson:"userId,omitempty"`
	Degree         string `json:"degree" bson:"degree,omitempty"`
	Institution    string `json:"institution" bson:"institution,omitempty"`
	GraduationYear string `json:"graduationYear" bson:"graduationYear,omitempty"`
}

type NewFile struct {
	UserID   string         `json:"userId" bson:"userId,omitempty"`
	File     graphql.Upload `json:"file" bson:"file,omitempty"`
	Title    string         `json:"title" bson:"title,omitempty"`
	Category string         `json:"category" bson:"category,omitempty"`
}

type NewNote struct {
	Title       string `json:"title" bson:"title,omitempty"`
	Description string `json:"description" bson:"description,omitempty"`
	CourseID    string `json:"courseId" bson:"courseId,omitempty"`
	URL         string `json:"url" bson:"url,omitempty"`
}

type NewQuiz struct {
	CourseID    string `json:"courseId" bson:"courseId,omitempty"`
	Title       string `json:"title" bson:"title,omitempty"`
	Description string `json:"description" bson:"description,omitempty"`
}

type NewReferee struct {
	UserID   string `json:"userId" bson:"userId,omitempty"`
	FullName string `json:"fullName" bson:"fullName,omitempty"`
	Email    string `json:"email" bson:"email,omitempty"`
	Phone    string `json:"phone" bson:"phone,omitempty"`
}

type NewSetting struct {
	Type *string `json:"type" bson:"type,omitempty"`
}

type NewUser struct {
	FirstName string `json:"firstName" bson:"firstName,omitempty"`
	LastName  string `json:"lastName" bson:"lastName,omitempty"`
	Email     string `json:"email" bson:"email,omitempty"`
	Password  string `json:"password" bson:"password,omitempty"`
}

type NewVideo struct {
	Title       string `json:"title" bson:"title,omitempty"`
	Description string `json:"description" bson:"description,omitempty"`
	CourseID    string `json:"courseId" bson:"courseId,omitempty"`
	URL         string `json:"url" bson:"url,omitempty"`
}

type Note struct {
	ID          string     `json:"id" bson:"_id"`
	Title       string     `json:"title" bson:"title,omitempty"`
	Description string     `json:"description" bson:"description,omitempty"`
	Text        string     `json:"text" bson:"text,omitempty"`
	CourseID    string     `json:"courseId" bson:"courseId,omitempty"`
	CreatedAt   *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
}

type Question struct {
	ID              string        `json:"id" bson:"_id"`
	QuestionType    *string       `json:"questionType" bson:"questionType,omitempty"`
	QuizID          *string       `json:"quizId" bson:"quizId,omitempty"`
	Question        *string       `json:"question" bson:"question,omitempty"`
	Description     *string       `json:"description" bson:"description,omitempty"`
	CorrectAnswerID *string       `json:"correctAnswerID" bson:"correctAnswerID,omitempty"`
	Quiz            *Quiz         `json:"quiz" bson:"quiz,omitempty"`
	Answer          *AnswerOption `json:"answer" bson:"answer,omitempty"`
}

type Quiz struct {
	ID          string      `json:"id" bson:"_id"`
	CourseID    string      `json:"courseId" bson:"courseId,omitempty"`
	Title       string      `json:"title" bson:"title,omitempty"`
	Description string      `json:"description" bson:"description,omitempty"`
	QuizType    *string     `json:"quizType" bson:"quizType,omitempty"`
	TargetID    *string     `json:"targetId" bson:"targetId,omitempty"`
	Questions   []*Question `json:"questions" bson:"questions,omitempty"`
	CreatedAt   *time.Time  `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt   *time.Time  `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt   *time.Time  `json:"deletedAt" bson:"deletedAt,omitempty"`
}

type Referee struct {
	ID        string     `json:"id" bson:"_id"`
	UserID    string     `json:"userId" bson:"userId,omitempty"`
	FullName  string     `json:"fullName" bson:"fullName,omitempty"`
	Email     string     `json:"email" bson:"email,omitempty"`
	Phone     string     `json:"phone" bson:"phone,omitempty"`
	CreatedAt *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
}

type Role struct {
	ID          string        `json:"id" bson:"_id"`
	Name        *string       `json:"name" bson:"name,omitempty"`
	Permissions []interface{} `json:"permissions" bson:"permissions,omitempty"`
}

type Setting struct {
	ID     string   `json:"id" bson:"_id"`
	UserID string   `json:"userId" bson:"userId,omitempty"`
	Type   *string  `json:"type" bson:"type,omitempty"`
	Roles  []string `json:"roles" bson:"roles,omitempty"`
}

type Target struct {
	ID                     string             `json:"id" bson:"_id"`
	Role                   *Role              `json:"role" bson:"role,omitempty"`
	Title                  *string            `json:"title" bson:"title,omitempty"`
	Description            *string            `json:"description" bson:"description,omitempty"`
	CompletionInstructions *string            `json:"completionInstructions" bson:"completionInstructions,omitempty"`
	ResourceURL            *string            `json:"resourceURL" bson:"resourceURL,omitempty"`
	TargetGroupID          *string            `json:"targetGroupID" bson:"targetGroupID,omitempty"`
	SortIndex              *int               `json:"sortIndex" bson:"sortIndex,omitempty"`
	SessionAt              *time.Time         `json:"sessionAt" bson:"sessionAt,omitempty"`
	LinkToComplete         *string            `json:"linkToComplete" bson:"linkToComplete,omitempty"`
	Resubmittable          *bool              `json:"resubmittable" bson:"resubmittable,omitempty"`
	CheckList              []*string          `json:"checkList" bson:"checkList,omitempty"`
	ReviewChecklist        []*string          `json:"reviewChecklist" bson:"reviewChecklist,omitempty"`
	TargetGroup            *TargetGroup       `json:"targetGroup" bson:"targetGroup,omitempty"`
	TargetVersions         *TargetVersionList `json:"targetVersions" bson:"targetVersions,omitempty"`
	Quizzes                []*Quiz            `json:"Quizzes" bson:"Quizzes,omitempty"`
}

type TargetGroup struct {
	ID string `json:"id" bson:"_id"`
}

type TargetVersionList struct {
	ID string `json:"id" bson:"_id"`
}

type Thumbnail struct {
	ID      string `json:"id" bson:"_id"`
	VideoID string `json:"videoId" bson:"videoId,omitempty"`
	URL     string `json:"url" bson:"url,omitempty"`
}

type Timeline struct {
	ID       string `json:"id" bson:"_id"`
	CourseID string `json:"courseId" bson:"courseId,omitempty"`
}

type UpdateRole struct {
	ID          string        `json:"id" bson:"_id"`
	Name        *string       `json:"name" bson:"name,omitempty"`
	Permissions []interface{} `json:"permissions" bson:"permissions,omitempty"`
}

type UpdateSetting struct {
	Name        *string   `json:"name" bson:"name,omitempty"`
	Permissions []*string `json:"permissions" bson:"permissions,omitempty"`
}

type UploadFile struct {
	File graphql.Upload `json:"file" bson:"file,omitempty"`
}

type User struct {
	ID                     string     `json:"id" bson:"_id"`
	FirstName              string     `json:"firstName" bson:"firstName,omitempty"`
	LastName               string     `json:"lastName" bson:"lastName,omitempty"`
	MiddleName             string     `json:"middleName" bson:"middleName,omitempty"`
	FullName               string     `json:"fullName" bson:"fullName,omitempty"`
	Email                  string     `json:"email" bson:"email,omitempty"`
	Phone                  string     `json:"phone" bson:"phone,omitempty"`
	AvatarURL              string     `json:"avatarUrl" bson:"avatarUrl,omitempty"`
	Dob                    string     `json:"dob" bson:"dob,omitempty"`
	Gender                 string     `json:"gender" bson:"gender,omitempty"`
	Address                string     `json:"address" bson:"address,omitempty"`
	City                   string     `json:"city" bson:"city,omitempty"`
	State                  string     `json:"state" bson:"state,omitempty"`
	Country                string     `json:"country" bson:"country,omitempty"`
	Zip                    string     `json:"zip" bson:"zip,omitempty"`
	Nationality            string     `json:"nationality" bson:"nationality,omitempty"`
	Profession             string     `json:"profession" bson:"profession,omitempty"`
	PasswordSalt           string     `json:"passwordSalt" bson:"passwordSalt,omitempty"`
	PasswordHash           string     `json:"passwordHash" bson:"passwordHash,omitempty"`
	Role                   string     `json:"role" bson:"role,omitempty"`
	Permissions            []*string  `json:"permissions" bson:"permissions,omitempty"`
	Username               string     `json:"username" bson:"username,omitempty"`
	IsVerified             bool       `json:"isVerified" bson:"isVerified,omitempty"`
	About                  string     `json:"about" bson:"about,omitempty"`
	Wallet                 float64    `json:"wallet" bson:"wallet,omitempty"`
	TimeZone               string     `json:"timeZone" bson:"timeZone,omitempty"`
	Progress               int        `json:"progress" bson:"progress,omitempty"`
	Token                  string     `json:"token" bson:"token,omitempty"`
	TokenExpiredAt         int64      `json:"tokenExpiredAt" bson:"tokenExpiredAt,omitempty"`
	MatricNumber           string     `json:"matricNumber" bson:"matricNumber,omitempty"`
	Platform               string     `json:"platform" bson:"platform,omitempty"`
	Program                string     `json:"program" bson:"program,omitempty"`
	RegNumber              string     `json:"regNumber" bson:"regNumber,omitempty"`
	Files                  []string   `json:"files" bson:"files,omitempty"`
	Courses                []string   `json:"courses" bson:"courses,omitempty"`
	SalvationBrief         string     `json:"salvationBrief" bson:"salvationBrief,omitempty"`
	GodsWorkings           []string   `json:"godsWorkings" bson:"godsWorkings,omitempty"`
	Reason                 string     `json:"reason" bson:"reason,omitempty"`
	ChurchName             string     `json:"churchName" bson:"churchName,omitempty"`
	ChurchAddress          string     `json:"churchAddress" bson:"churchAddress,omitempty"`
	PastorName             string     `json:"pastorName" bson:"pastorName,omitempty"`
	PastorEmail            string     `json:"pastorEmail" bson:"pastorEmail,omitempty"`
	PastorPhone            string     `json:"pastorPhone" bson:"pastorPhone,omitempty"`
	ChurchInvolved         string     `json:"churchInvolved" bson:"churchInvolved,omitempty"`
	HealthConditions       []string   `json:"healthConditions" bson:"healthConditions,omitempty"`
	HealthIssueDescription string     `json:"healthIssueDescription" bson:"healthIssueDescription,omitempty"`
	Scholarship            *bool      `json:"scholarship" bson:"scholarship,omitempty"`
	ScholarshipReason      string     `json:"scholarshipReason" bson:"scholarshipReason,omitempty"`
	Qualifications         []string   `json:"qualifications" bson:"qualifications,omitempty"`
	Referees               []string   `json:"referees" bson:"referees,omitempty"`
	CreatedAt              *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt              *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt              *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
	ConfirmedAt            *time.Time `json:"confirmedAt" bson:"confirmedAt,omitempty"`
	ConfirmationMailSentAt *time.Time `json:"confirmationMailSentAt" bson:"confirmationMailSentAt,omitempty"`
}

type Video struct {
	ID          string     `json:"id" bson:"_id"`
	Title       string     `json:"title" bson:"title,omitempty"`
	Description string     `json:"description" bson:"description,omitempty"`
	URL         string     `json:"url" bson:"url,omitempty"`
	CourseID    string     `json:"courseId" bson:"courseId,omitempty"`
	Thumbnail   *Thumbnail `json:"thumbnail" bson:"thumbnail,omitempty"`
	Related     []*Video   `json:"related" bson:"related,omitempty"`
	CreatedAt   *time.Time `json:"createdAt" bson:"createdAt,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt" bson:"updatedAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt" bson:"deletedAt,omitempty"`
}

type NewMail struct {
	FromAddr string      `json:"FromAddr" bson:"FromAddr,omitempty"`
	ToAddrs  []string    `json:"toAddrs" bson:"toAddrs,omitempty"`
	Subject  string      `json:"subject" bson:"subject,omitempty"`
	Body     string      `json:"body" bson:"body,omitempty"`
	Data     interface{} `json:"data" bson:"data,omitempty"`
}
